apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data

  # volumeMode: Filesystem
  # persistentVolumeReclaimPolicy: Recycle | Retain (default) | Delete


  # awsElasticBlockStorage
  #     volumeID: <someID>
  #     fsType: ext4
