apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset1
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      name: nginx-daemon
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: nginx

