apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginxrs
  labels:
    app: nginx
spec: 
  replicas: 3
  selector: 
    matchExpressions:
      - key: app
        operator: In
        values: [nginx_1, nginx_2]
  template:
    metadata:
      name: nginx
      labels:
        app: nginx_2 
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
              name: nginx
